// Domain types — re-exported from the shared @fitforge/types package
export type {
  EquipmentOption,
  UserProfile,
  Muscle,
  Exercise,
  WorkoutTemplate,
  TemplateExercise,
  WorkoutSession,
  ExerciseEntry,
  ExerciseSet,
  CardioSession,
  WeightEntry,
  BodyMeasurement,
  TrainingPlan,
  PersonalRecord,
  CoachConversation,
  CoachMessage,
  CoachContext,
} from "@fitforge/types";
